server:
  host: 127.0.0.1
  port: 3000
mysql:
  username: root
  password: gochat123
  host: 127.0.0.1
  port: 33306
  dbname: go-chat
  charset: utf8mb4
  parseTime: True
  loc: Local 
redis:
  host: 127.0.0.1
  port: 36379
  db: 0
  password:
jwt:
  secret: jwt-secret
  expire: 24